// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
// app/layout.js
export default function RootLayout({ children, team, analytics }) {
  return (
    <html>
      <body>
        <h1>root layout</h1>
        {children}
        {team}
        {analytics}
      </body>
    </html>
  )
}